# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_facebook: &default_facebook
  facebook_key: 1662122164115121
  facebook_secret: 04b8a48f1b9c185b31cb294406680181
default_google: &default_google
  google_oauth2_key: 265098974016-8lud85g3vt5r79jf7saeg27u0qscdn5u.apps.googleusercontent.com
  google_oauth2_secret: mFodi-v2Oq4AZq_QFT271GWY
default_twitter: &default_twitter
  twitter_key: vKz011Lx017SORfImYyQeqtkk
  twitter_secret: KLhAcbKubzDyKp5nJSWaK17j3vWCm8IQbQrheFOdx4GcG3SgWF


# ---
# ---


development:
  secret_key_base: 17b02f9c773eb219206266a3bf75fb45208df508937fa8f5acb594ead0ba9beea4133ef172b8347d864c2861003c7302906e6e58c0625db21092c7e4218407a0
  <<: *default_facebook
  <<: *default_google
  <<: *default_twitter

test:
  secret_key_base: c42ee91f0fb3c75688d7a2819ff220fb4f6d73234817813578ac972a4d08433621ad14f6adc66518248748811c3acb0b508afdb4bfd79be85fb9e882c00b4033
  <<: *default_facebook
  <<: *default_google
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["GOOGLE_KEY"] %>
  google_oauth2_secret: <%= ENV["GOOGLE_SECRET"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
